### ISSUE TITLE
fishroom may need at least python 3.5

### ISSUE THREAD

**Issue by mytbk** [tuna/fishroom#55]
README.md says "Ensure your python version is at least 3.4". However, Python 3.4.3 from Ubuntu 14.04 cannot run fishroom.

In fishroom/bus.py, there is an ``import typing``, which is new in version Python 3.5.

https://docs.python.org/3/library/typing.html

Also I have the following error when running the latest git code.

```
root@redis-512mb-sfo1-01:~/fishroom# python3 -m fishroom.fishroom
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/fishroom/fishroom/fishroom.py", line 8, in <module>
    from .base import EmptyBot
  File "/root/fishroom/fishroom/base.py", line 73
    raw=msg, **msg.opt,
                      ^
SyntaxError: invalid syntax
```

**Comment by bigeagle** [comment]
Oh, my fault. Yes, fishroom needs at least python 3.5.
