### ISSUE TITLE
Wechat module crashed after sending messages in web.

### ISSUE THREAD

**Issue by simonsmh** [tuna/fishroom#72]
Traceback (most recent call last):
  File "/root/fishroom/fishroom/runner.py", line 37, in wrapper
    f(*args, **kwargs)
  File "/root/fishroom/fishroom/wechat.py", line 230, in Fishroom2WechatThread
    myid_chn = config[msg.channel].get("me")
KeyError: 'web'
@mytbk

**Comment by mytbk** [comment]
呃，当初测试的时候没试过web端。
是这样的，我当时写这个的考虑是我会拿自己的微信号来做机器人，所以希望我自己的{Matrix,XMPP,...}发消息的时候机器人不会加一个[username]的串，所以才会考虑用config[channel]['me']这个属性。
