### ISSUE TITLE
Failed start fishroom.web

### ISSUE THREAD

**Issue by Parrotseccn** [tuna/fishroom#82]
redis是用apt install redis-server 安装的,config.py中redis的host改成了127.0.0.1,之前的步骤都没有报错

启动fishroom.fishroom的回显是:

```
root@hostker:~/fishroom# python3 -m fishroom.fishroom
[fishroom.command] [INFO] command `help` registered
[fishroom.command] [INFO] command `pia` registered
[fishroom.command] [INFO] command `mua` registered
[fishroom.command] [INFO] command `imglink` registered
[fishroom.command] [INFO] command `vote` registered
[fishroom.command] [INFO] command `hualao` registered
```

然后尝试启动fishroom.web出现错误
```
root@hostker:~/fishroom# python3 -m fishroom.web
[fishroom.command] [INFO] command `help` registered
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/fishroom/fishroom/web/__main__.py", line 30, in <module>
    main()
  File "/root/fishroom/fishroom/web/__main__.py", line 24, in main
    application.listen(config['chatlog']['port'],address=config['chatlog'].get('host', '0.0.0.0'))
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1944, in listen
    server.listen(port, address)
  File "/usr/local/lib/python3.5/dist-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.5/dist-packages/tornado/netutil.py", line 156, in bind_sockets
    0, flags)):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by Parrotseccn** [comment]
已经解决
